- build.gradle
#13 
`dependencies` 버전을 명시하였습니다.
`spring-boot-starter-web`: 3.0.1
`lombok`: 1.18.24
`mysql-connector-j`: 8.0.31
`jdbc`: 3.0.1
`jpa`: 3.0.1
`flyway-mysql`: 9.11.0
`spring-boot-test`: 3.0.1
> build: dependencies version settings

- build.gradle
- config/checkstyle/checkstyle.xml
- config/checkstyle/suppressions.xml
- config/checkstyle/suppressions_1_2.dtd
- src/main/java/com/dnd/wedding/WeddingApplication.java
- src/test/java/com/dnd/wedding/WeddingApplicationTests.java
#12 
- 체크스타일 설정을 위한 파일 추가
- 체크스타일 플러그인 추가
- 체크스타일에 맞춰 indent 사이즈를 2 space로 수정
그래들 탭에서 위 메뉴를 클릭하면 실행됩니다.
> build: use checkstyle to validate code convension

- .github/workflows/api-docs.yml
#24 
`GitHub Actions`를 활용하여 문서화 페이지를 빌드하고 배포합니다.
현재는 문서화 페이지를 빌드하기 위해 `./gradle build` 명령어를 이용하여 프로젝트 전체를 빌드해야 합니다.
결국 문서화 페이지를 배포하는 데까지의 시간을 지체시키고 있습니다.
가능하다면 문서화 페이지만 빌드하는 `Gradle task`를 생성하는 것이 좋을 것 같습니다.
> build: api documentation page deployment

- config/checkstyle/suppressions.xml
#29 
`OAuth` 관련 클래스의 네이밍 컨벤션 체크를 비활성화하여 `OAuth`에 대한 클래스는 1개 이상의 연속 대문자를 허용합니다.
> chore: disable naming convention check for class associated with OAuth

- docker-compose.local.yml
- docker-compose.yml
- src/main/java/com/dnd/wedding/WeddingApplication.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
#34 
로컬환경과 배포환경에 따른 설정파일을 분리하였습니다.
앞으로 설정파일은 다음과 같이 사용해주시면 됩니다.
- application.yml
- 모든 환경에서 사용되는 공통된 설정
- application-local.yml
- 로컬 환경에서 필요한 설정
- application-prod.yml
- 배포 환경에서 필요한 설정
- 모든 `credential` 정보들은 `환경변수`로 지정
이와 동시에 docker-compose도 로컬과 배포환경을 분리하였습니다.
- docker-compose.local.yml
- 로컬에서 사용하는 컴포즈 파일
- docker-compose.yml
- 배포 환경에서 사용하는 컴포즈 파일
> **Note** 모든 로컬에서 필요한 테스트용 설정은 노출되어도 무방합니다.
> **Warning** 로컬 환경에서는 다음과 같은 설정을 진행해주셔야 합니다.
구성편집 클릭
프로파일에 local이라고 입력
> chore: separating settings files based on profile

- build.gradle
- src/test/resources/application.yml
#36 
테스트 코드 동작시 데이터베이스를 H2 인메모리를 사용하도록 설정합니다.
스프링 상에서 @DataJpaTest 어노테이션을 사용해 레포지토리에 대한 테스트를 실행하면 기본적으로 H2를 사용하므로 설정 파일 상에 별도로 명시하지 않았습니다.
> chore: set in memory db for test environment

- .github/workflows/api-docs.yml
- .github/workflows/ci.yml
#40 
깃헙 액션의 트리거를 수정하여 문서가 프로덕션에 적용된 API만을 제공하도록 합니다.
추가로 SonarCloud가 develop 브랜치 이벤트에도 동작하도록 설정합니다.
> build: change github action workflow trigger

- src/main/java/com/dnd/wedding/domain/jwt/JwtTokenProvider.java
- src/main/java/com/dnd/wedding/domain/jwt/RefreshToken.java
- src/main/java/com/dnd/wedding/domain/jwt/controller/JwtController.java
- src/main/java/com/dnd/wedding/domain/jwt/repository/RefreshTokenRedisRepository.java
- src/main/java/com/dnd/wedding/domain/jwt/service/JwtService.java
- src/main/java/com/dnd/wedding/global/config/RedisConfig.java
- src/main/java/com/dnd/wedding/global/config/SecurityConfig.java
- src/test/java/com/dnd/wedding/domain/jwt/controller/JwtControllerTest.java
- src/test/java/com/dnd/wedding/domain/jwt/service/JwtServiceTest.java
#27 
`refresh token`을 사용해 만료된 `access token`을 갱신하는 로직을 추가하였습니다.
> feat: renew authentication token

- src/main/java/com/dnd/wedding/domain/jwt/JwtAuthenticationFilter.java
- src/main/java/com/dnd/wedding/domain/jwt/controller/JwtController.java
- src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/com/dnd/wedding/global/config/util/CookieUtil.java
None
- `isAuthorizedRedirectUri` 함수 내 리턴문 단순화
- `CookieUtil` 클래스 내 조건문 단순화
- `CookieUtil` 클래스 내 public 생성자 제거
- `JwtAuthenticationFilter` 내 boxed boolean 제거
- `JwtController` 내 제네릭 파라미터 추가
> refactor: reduce code smells

- src/main/java/com/dnd/wedding/global/config/util/CookieUtil.java
#45 
기존에 작성했던 `SerializationUtils.deserialize` 함수가 **deprecated**되어  `java.io`의 `ObjectInputStream`을 사용하는 방법으로 변경하였습니다.
[참고 글](https://steady-coding.tistory.com/576)
> fix: change cookie deserialize function from CookieUtil

- src/main/java/com/dnd/wedding/global/config/SecurityConfig.java
None
**CSRF** 설정으로 인해 Get 요청을 제외한 나머지 HTTP 요청에서 모두 401 상태 코드를 반환합니다.
**REST API**는 **CSRF**와 관련이 없으므로 `SecurityConfig`에 `csrf().disable()`을 추가하였습니다.
> feat: change csrf setting to disabled

- src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/com/dnd/wedding/global/config/SecurityConfig.java
None
redirect uri 설정을 위해 `SecurityConfig`의 `authorizationRequestRepository`로 `CookieAuthorizationRequestRepository`를 설정해주었습니다.
Google 로그인 요청 시 url의 파라미터로 **redirect_uri**를 추가해주시면 됩니다.
예시)
`http://localhost:8080/oauth2/authorization/google?redirect_uri=http://localhost:8080/oauth2/redirect`
> fix: add authorizationRequestRepository setting to SecurityConfig

- src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/com/dnd/wedding/global/exception/BadRequestException.java
- src/main/java/com/dnd/wedding/global/exception/ControllerExceptionHandler.java
- src/main/java/com/dnd/wedding/global/exception/ErrorMessage.java
- src/main/java/com/dnd/wedding/global/exception/ForbiddenException.java
- src/main/java/com/dnd/wedding/global/exception/InternalServerErrorException.java
- src/main/java/com/dnd/wedding/global/exception/NotFoundException.java
- src/main/java/com/dnd/wedding/global/exception/UnauthorizedException.java
- src/test/java/com/dnd/wedding/domain/jwt/JwtTokenProviderTest.java
- src/test/java/com/dnd/wedding/global/exception/ControllerExceptionHandlerTest.java
None
전역적인 예외처리를 위해 `ErrorMessage` 포맷을 정의하고 `ControllerAdvice`를 사용한 `ControllerExceptionHandler`를 추가하였습니다. `@ExceptionHandler` 어노테이션을 통해 예외에 대한 처리를 추가하여 사용할 수 있습니다.
이는 Controller 전역에서 사용 가능하며 이외의 Service 로직에서는 동작하지 않습니다.
> 잘못된 요청: BadRequestException
> 인증되지 않은 사용자: UnauthorizedException
> 접근 권한 없음: ForbiddenException
> 존재하지 않는 리소스: NotFoundException
> 서버 내부 오류: InternalServerErrorException
> feat: add exception handler used ControllerAdvice

- build.gradle
None
DTO 및 데이터에 대한 validation 어노테이션을 사용하기 위해 `org.springframework.boot:spring-boot-starter-validation:3.0.2`를 추가하였습니다.
> build: add validation dependency

- src/main/java/com/dnd/wedding/domain/jwt/JwtTokenProvider.java
- src/main/java/com/dnd/wedding/domain/oauth/CustomUserDetails.java
- src/main/java/com/dnd/wedding/domain/oauth/service/CustomOAuth2UserService.java
- src/test/java/com/dnd/wedding/domain/jwt/JwtTokenProviderTest.java
- src/test/java/com/dnd/wedding/domain/jwt/service/JwtServiceTest.java
- src/test/java/com/dnd/wedding/domain/oauth/CustomUserDetailsTest.java
- src/test/java/com/dnd/wedding/global/WithMockOAuth2UserSecurityContextFactory.java
#65 
- `CustomUserDetails` 구조 개선
- 기존에 `getUserName()` 메서드가 이메일을 리턴했는데 코드 의미상 맞지 않다고 판단하여 해당 메서드는 실제 유저 이름을 반환하게 하였습니다.
- 대신 추가적인 `getEmail()`이라는 메서드를 생성하였습니다.
> refactor: improve custom user details structure

- src/docs/asciidoc/api/Authorization.adoc
- src/docs/asciidoc/index.adoc
- src/main/java/com/dnd/wedding/domain/jwt/JwtAuthenticationFilter.java
- src/main/java/com/dnd/wedding/domain/jwt/JwtTokenProvider.java
- src/main/java/com/dnd/wedding/domain/jwt/controller/JwtController.java
- src/main/java/com/dnd/wedding/domain/jwt/dto/AccessTokenResponse.java
- src/main/java/com/dnd/wedding/domain/jwt/repository/CookieAuthorizationRequestRepository.java
- src/main/java/com/dnd/wedding/domain/jwt/service/JwtService.java
- src/main/java/com/dnd/wedding/domain/oauth/CustomUserDetails.java
- src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationFailureHandler.java
- src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/com/dnd/wedding/domain/oauth/service/CustomUserDetailsService.java
- src/main/java/com/dnd/wedding/global/config/SecurityConfig.java
- src/main/java/com/dnd/wedding/global/util/CookieUtil.java
- src/main/java/com/dnd/wedding/global/util/HeaderUtil.java
- src/test/java/com/dnd/wedding/domain/jwt/JwtTokenProviderTest.java
- src/test/java/com/dnd/wedding/domain/jwt/controller/JwtControllerTest.java
- src/test/java/com/dnd/wedding/domain/oauth/CustomUserDetailsTest.java
- src/test/java/com/dnd/wedding/global/util/CookieUtilTest.java
None
- `CustomUserDetailsService` 추가
- JwtProvider 내 `getAuthentication` 메서드가 유저 Principal을 가져올 때 loadUserByUsername 메서드를 이용하도록 수정
- util 패키지 경로 변경
- `global/config/util` -> `global/util`
- 헤더 정보 파싱을 위한 HeaderUtil 추가
- 기존의 `JwtAuthenticationFilter` 내 `parseBearerToken` 함수를 `getAccessToken`으로 변경 후 이동
- `AccessToken` 재발급 시 요청 메서드 `POST`로 변경
- `AccessToken` 재발급 시 응답 형식 `SuccessResponse`로 변경
- 문서화 페이지 생성
> refactor: improve jwt token process

- .github/workflows/api-docs.yml
#71 
문서화 패이지 배포 기준을 `develop` 브랜치 머지로 변경합니다.
> build: change documentation deployment trigger

- src/main/java/com/dnd/wedding/global/config/SecurityConfig.java
None
JWT refresh api 요청시 액세스 토큰 만료를 검사하지 않도록 설정
> hotfix: allow jwt refresh api without authenticated

- src/docs/asciidoc/api/Authorization.adoc
- src/test/java/com/dnd/wedding/domain/jwt/controller/JwtControllerTest.java
> docs: update jwt api

- src/main/java/com/dnd/wedding/domain/checklist/checklistitem/controller/ChecklistItemController.java
- src/main/java/com/dnd/wedding/domain/checklist/controller/ChecklistController.java
- src/main/java/com/dnd/wedding/domain/member/service/MemberService.java
- src/main/java/com/dnd/wedding/domain/member/service/impl/MemberServiceImpl.java
- src/test/java/com/dnd/wedding/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
- src/test/java/com/dnd/wedding/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
- src/test/java/com/dnd/wedding/domain/checklist/controller/ChecklistControllerTest.java
None
`MemberService`의 `findMember` 함수를 추가하였습니다.
Checklist 관련 controller에서 사용하던 `MemberRepository`를 `MemberService`로 변경하였습니다.
> refactor: change dependency for member in checklist controller

- src/test/java/com/dnd/wedding/domain/member/controller/MemberControllerTest.java
None
사용자 API의 액세스 토큰 값을 변경하였습니다.
`accessToken` -> `ACCESS_TOKEN`
> docs: change access token value in member api

- src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
None
- `authorizedRedirectUri` 의 환경변수명을 변경
- 기존의 `GOOGLE_OAUTH2_REDIRECT_URI`는 구글로 제한하는 이름인 것 같아 변경하였습니다.
- `authorizedRedirectUri`를 `authorized-redirect-uri`로 변경
- `refresh-cookie-key` 을 공통 설정으로 변경
- 환경을 구분할 필요가 없을 것 같습니다.
> chore: update project configurations

- src/main/java/com/dnd/wedding/global/exception/ControllerExceptionHandler.java
- src/test/java/com/dnd/wedding/domain/oauth/info/OAuth2UserInfoFactoryTest.java
- src/test/java/com/dnd/wedding/global/exception/ControllerExceptionHandlerTest.java
#62 
spring security로 인해 다른 에러임에도 `401 Unauthorized`을 반환하는 에러에 대한 handler를 추가하였습니다. 
- HttpRequestMethodNotSupportedException
- MethodArgumentNotValidException
- Exception
> bug: return unauthorized when undefined error occurs

- src/test/java/com/dnd/wedding/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
- src/test/java/com/dnd/wedding/domain/checklist/controller/ChecklistControllerTest.java
None
`LocalTime.now()`나 `MIN`, `MAX` 등을 사용할 경우 api 문서에 ms까지 표기되는 문제가 있어 실제 구체적인 값으로 수정하였습니다.
> test(checklist): change time to actual value

- src/docs/asciidoc/api/checklist/checklist.adoc
- src/main/java/com/dnd/weddingmap/domain/checklist/PreChecklistItem.java
- src/main/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistController.java
- src/main/java/com/dnd/weddingmap/domain/checklist/dto/PreChecklistItemListDto.java
- src/main/java/com/dnd/weddingmap/domain/checklist/service/ChecklistService.java
- src/main/java/com/dnd/weddingmap/domain/checklist/service/impl/ChecklistServiceImpl.java
- src/test/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistControllerTest.java
#84 
온보딩에서 사용할 체크리스트 사전 등록 api입니다.
온보딩 페이지에서 선택되지 않은 항목들에 대한 체크리스트를 사전 등록합니다.
- 상견례 **MEETING**
- 예식장 **WEDDING_HALL**
- 신혼여행 **HONEYMOON**
- 스튜디오 **STUDIO**
- 드레스 **DRESS**
- 메이크업 **MAKEUP**
- 예물 **WEDDING_GIFT**
> feat: onboarding checklist pre check api

- .github/workflows/cd.yml
- build.gradle
- task-definition.json
#25
- 배포 자동화를 위한 `GitHub Actions` 워크플로우를 작성하였습니다.
- 도커 이미지 빌드를 위해 [GoogleContainerTools/jib](https://github.com/GoogleContainerTools/jib)을 사용하였습니다.
- 배포 시 필요한 `task-definition.json` 파일을 추가하였습니다.
깃헙 액션이 수행하는 워크플로우는 다음과 같습니다.
```mermaid
flowchart TD
.[GitHub Actions]
. --> |1. Setup credentials| 1[AWS Credentials] --> 2[Login ECR]
. --> |2. Prepare container image| a[Set Up Java] --> b[Jib] --> |Image Build & Push| c[Amazon ECR]
. --> |3. Deploy application| A[Task Definition] --> |Use task-definition.json| B[Amazon ECS]
```
1. `AWS Credentials` 설정
2. `Amazon ECR` 로그인
3. 자바 설정 - Jib 실행을 위해 필요
5. `Jib`을 사용하여 `도커 이미지 빌드` 및 `ECR에 배포`
6. `task-definition`을 이용하여 `서비스 배포`
> build: deploy applicaition using GitHub Actions

- src/docs/asciidoc/api/checklist/checklist.adoc
- src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/repository/ChecklistItemRepository.java
- src/main/java/com/dnd/weddingmap/domain/checklist/service/impl/ChecklistServiceImpl.java
- src/test/java/com/dnd/weddingmap/domain/checklist/checklistitem/repository/ChecklistItemRepositoryTest.java
None
체크리스트 조회 시 응답 데이터를 **일정 날짜(checkDate)** 순으로 정렬하여 보내도록 수정하였습니다.
> fix: change response data to sort by date

- .github/workflows/api-docs.yml
- .github/workflows/ci.yml
None
깃헙 액션 최적화 작업 진행
- 자바 배포판 `temurin`으로 변경
- `CI` 워크플로우 gradle 캐시를 `setup-java`의 설정으로 처리
> build: optimize GitHub actions

- build.gradle
- src/main/java/com/dnd/weddingmap/global/config/SecurityConfig.java
#96 
- health check api를 추가하기 위한 `Spring Boot Starter Actuator` 의존성 설정
- `/actuator/health` url 요청 모두 허용
`/actuator/health`로 GET 요청 시 Actuator는 서버가 정상 가동 중인지 확인하여 응답합니다.
> feature: health check api

- task-definition.json
#107 
- `awslogs`를 설정하여 컨테이너 내 에러 로그를 확인할 수 있도록 함
- `task-definition` 내 설정할 필요 없는 필드 제거
> build: update ecs task definition

- task-definition.json
#109 
프로덕션 서버에서 발생한 에러를 해결하기 위해 애플리케이션 컨테이너를 업그레이드합니다.
- `vCPU` : 0.25 → 0.75
- `memory` : 0.25 → 0.75
> fix: resolve out of memory on ecs container

- src/docs/asciidoc/api/budget/transaction.adoc
#113 
예산표 api 문서의 잘못된 타이틀을 수정하였습니다.
> docs: modify wrong title in transaction api

- src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemController.java
- src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/service/ChecklistItemService.java
- src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/service/impl/ChecklistItemServiceImpl.java
- src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemController.java
- src/test/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
- src/test/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
#124
checklistItem 접근 시 user 확인 로직을 추가하였습니다.
> refactor: add permission check logic for checklist

- src/main/java/com/dnd/weddingmap/global/config/SecurityConfig.java
- src/main/java/com/dnd/weddingmap/global/config/WebConfig.java
- src/main/resources/application.yml
- src/test/java/WeddingMapApplicationTest.java
- src/test/resources/application.yml
#115 
프론트엔드 URL간 통신을 위한 추가적인 CORS 설정입니다.
`ORIGIN_URL`이라는 환경변수에 프론트 주소를 설정하면 됩니다.
> chore: allow front-end domain cors

- build.gradle
#119 
- `Spring Boot` 버전을 `v3.0.3`으로 업그레이드
- `Spring Security Test` 버전을 `v6.0.2`으로 업그레이드
> build: upgrade spring boot to v3.0.3

- task-definition.json
#151 
배포 시 발생하는 에러를 해결합니다.
- `nginx` 컨테이너 사이즈 축소
- 컨테이너 용량을 타이트하게 잡았더니 배포가 안되는 문제가 있었습니다.
- `task-definition.json` 내 후행 콤마 제거
> fix: ecs deployment fail

- src/docs/asciidoc/api/checklist/checklist.adoc
- src/main/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistController.java
- src/main/java/com/dnd/weddingmap/domain/checklist/service/ChecklistService.java
- src/main/java/com/dnd/weddingmap/domain/checklist/service/impl/ChecklistServiceImpl.java
- src/test/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistControllerTest.java
#163 
체크리스트 조회 시 서브 아이템 조회 유무를 `query`를 사용하여 선택할 수 있도록 수정하였습니다.
> refactor: add subitem option to checklist api

- src/main/java/com/dnd/weddingmap/domain/jwt/JwtAuthenticationFilter.java
#74 
`JWT Authentication Filter`에서 `Access Token`이 `Null`인 경우를 처리하지 않아 발생한 에러를 해결하였습니다.
> fix(jwt): JWT String argument cannot be null or empty
