dnd-side-project/dnd-8th-8-backend

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml, .github/PULL_REQUEST_TEMPLATE.md
=> chore: Add templates for contribution

.gitignore
#3 
- 주석을 사용하여 `.gitignore`의 섹션 구분
- `.idea` 폴더를 무시하도록 추가
=> chore: Add idea directory to .gitignore

.github/workflows/ci.yml
#7 
`SonarCloud`와 연동하기 위한 워크플로우를 생성하였습니다.
=> build(ci): add sonarqube github actions workflow

config/intellij-java-google-style.xml
#17
인텔리제이의 포매터에 적용하기 위한 `구글 스타일 설정 파일`을 추가하였습니다.
=> chore: add intellij java google style configuration file

docker-compose.yml
None
도커 컴포즈 상 타임존이 잘못 설정되어 있어 수정하였습니다.
=> fix: db timezone in docker-compose

.github/workflows/api-docs.yml, build.gradle
#28 
그래들 빌드를 전체를 진행하지 않고 `asciidoctor` task만을 실행하여 문서화를 진행하도록 수정하였습니다.
대신 필요없는 task들은 제거하였습니다.
=> build: improve spring rest docs task

src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml
None
- flyway 설정을 datasource의 속성과 연동
- 프로덕션 설정에 flyway 추가
- 구글 OAuth2 설정 프로퍼티 키를 케밥 케이스에 맞게 수정
=> refactor: improve application configurations

build.gradle, docker-compose.local.yml, docker-compose.yml, src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/dnd/wedding/domain/oauth/info/OAuth2UserInfo.java, src/test/java/com/dnd/wedding/domain/jwt/JwtTokenProviderTest.java, src/test/java/com/dnd/wedding/domain/jwt/service/JwtServiceTest.java, src/test/java/com/dnd/wedding/domain/member/MemberTest.java, src/test/java/com/dnd/wedding/domain/oauth/CustomUserDetailsTest.java, src/test/java/com/dnd/wedding/global/config/util/CookieUtilTest.java
None
코드 전반에 대해서 개선 사항을 찾아 수정하였습니다.
- 사용하지 않는 import 문 제거
- 사용하지 않는 `@Autowired` 어노테이션 제거
- 되도록 해당 어노테이션은 사용하지 않도록 합니다. 
- `fianl`로 선언할 수 있는 변수는 상수로 변경
- 도커 설정 내 `포트 번호`에 쌍따옴표 추가
- CookieUtilTest 내 `null check` 추가
- `build.gradle` 내 `dependencies` 재정렬
- 스프링과 관련된 것들을 모아두었습니다.
- `build.gradle` 내 버전 표기 안된 의존성 수정
=> refactor: improve code quality

src/main/java/com/dnd/wedding/global/exception/ControllerExceptionHandler.java, src/main/java/com/dnd/wedding/global/response/ErrorMessage.java, src/main/java/com/dnd/wedding/global/response/ErrorResponse.java, src/main/java/com/dnd/wedding/global/response/SuccessResponse.java, src/test/java/com/dnd/wedding/global/exception/ControllerExceptionHandlerTest.java, src/test/java/com/dnd/wedding/global/response/SuccessResponseTest.java
None
리스폰스 클래스를 개선합니다.
- 에러 메시지 클래스를 리스폰스 패키지로 이동
- 기존 성공 리스폰스에 빌더 추가
=> refactor: improve response class

src/main/java/com/dnd/wedding/global/response/SuccessResponse.java, src/test/java/com/dnd/wedding/global/response/SuccessResponseTest.java
None
SuccessResponse가 다른 상태를 가질 수 있도록 수정합니다.
=> refactor: update success response to have custom status

src/docs/asciidoc/api/checklist/checklist.adoc, src/docs/asciidoc/api/checklist/checklistItem.adoc, src/docs/asciidoc/api/checklist/checklistSubItem.adoc, src/test/java/com/dnd/wedding/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java, src/test/java/com/dnd/wedding/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java, src/test/java/com/dnd/wedding/domain/checklist/controller/ChecklistControllerTest.java
None
api 문서 제목을 한글로 변경하였습니다.
요청 시 `Authorization field`에 대한 작업을 추가하였습니다.
=> docs: update checklist api

src/test/java/com/dnd/wedding/domain/member/controller/MemberControllerTest.java
None
액세스 토큰 값 변경이 누락되어 적용하였습니다.
=> docs: apply missing changes of access token value

src/main/java/com/dnd/weddingmap/domain/aws/service/S3Service.java, src/main/java/com/dnd/weddingmap/domain/member/controller/MemberController.java, src/main/java/com/dnd/weddingmap/global/service/S3Service.java, src/test/java/com/dnd/weddingmap/domain/member/controller/MemberControllerTest.java, src/test/java/com/dnd/weddingmap/global/service/S3ServiceTest.java
None
- S3 버킷에 업로드 시 디렉터리 지정이 가능하도록 설정
- 테스트 코드 함수명 변경
- `S3Service`를 글로벌 패키지로 이동
=> refactor: improve s3 service

src/docs/asciidoc/index.adoc
None
API 문서 페이지의 제목을 프로젝트명으로 변경하였습니다.
=> docs: update document page title to project name

README.md
#80 
- API 문서 페이지 정보 추가
- 시작하기 섹션 추가
=> docs: update readme to add project info

src/docs/asciidoc/api/OAuth2.adoc
None
OAuth2.0 관련 문서 수정 작업
- API 타이틀 변경
- 간편로그인 API -> OAuth2.0 API 
- 헤더 대신 테이블 제목으로 변경
- 쿼리 파라미터를 위한 헤더 제목 변경
- 전반적인 API 설명 변경
=> docs: update oauth2 api docs

src/main/java/com/dnd/weddingmap/global/service/S3Service.java
#117 
aws s3에 업로드한 파일을 삭제하기 위해 `S3Service`에 `delete` 함수를 추가하였습니다.
=> feat: add withdraw function to s3 service

src/docs/asciidoc/api/wedding.adoc, src/main/java/com/dnd/weddingmap/domain/wedding/Wedding.java, src/main/java/com/dnd/weddingmap/domain/wedding/dto/WeddingDayDto.java, src/main/java/com/dnd/weddingmap/domain/wedding/service/impl/WeddingServiceImpl.java, src/main/resources/db/migration/V202303011627__Add_preparing_column_to_wedding.sql, src/test/java/com/dnd/weddingmap/domain/wedding/controller/WeddingControllerTest.java, src/test/java/com/dnd/weddingmap/domain/wedding/service/WeddingServiceTest.java
#126 
결혼 API에 준비중인지에 대한 여부를 추가하였습니다.
=> refactor: add preparing field to wedding

src/docs/asciidoc/api/Member.adoc, src/main/java/com/dnd/weddingmap/domain/member/Member.java, src/main/java/com/dnd/weddingmap/domain/member/controller/MemberController.java, src/main/java/com/dnd/weddingmap/domain/member/dto/NameDto.java, src/main/java/com/dnd/weddingmap/domain/member/service/MemberService.java, src/main/java/com/dnd/weddingmap/domain/member/service/impl/MemberServiceImpl.java, src/test/java/com/dnd/weddingmap/domain/member/MemberRepositoryTest.java, src/test/java/com/dnd/weddingmap/domain/member/MemberTest.java, src/test/java/com/dnd/weddingmap/domain/member/controller/MemberControllerTest.java
#127 
사용자 이름을 수정하는 API를 추가합니다.
=> feature: modify username api

build.gradle
#136 
`Spring Restdocs Asciidoctor` 버전이 잘못되어 수정하였습니다.
=> fix: incorrect restdocs asciidoctor version

src/docs/asciidoc/api/budget/transaction.adoc, src/test/java/com/dnd/weddingmap/domain/transaction/controller/TransactionControllerTest.java
None
**예산표**를 **거래 내역**으로 수정하였습니다.
=> refactor: change budget table to transaction history

src/main/java/com/dnd/weddingmap/domain/transaction/controller/TransactionController.java, src/main/java/com/dnd/weddingmap/domain/transaction/service/TransactionService.java, src/main/java/com/dnd/weddingmap/domain/transaction/service/impl/TransactionServiceImpl.java, src/test/java/com/dnd/weddingmap/domain/transaction/controller/TransactionControllerTest.java, src/test/java/com/dnd/weddingmap/domain/transaction/service/TransactionServiceTest.java
None
`transaction`에 대한 접근 권한 확인 로직을 추가하였습니다.
=> refactor: add permission check for transaction

src/test/java/com/dnd/weddingmap/domain/contract/controller/ContractControllerTest.java
None
contrller 테스트의 잘못된 DisplayName을 수정하였습니다.
=> test: change display name

src/test/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java, src/test/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java, src/test/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistControllerTest.java, src/test/java/com/dnd/weddingmap/domain/contract/controller/ContractControllerTest.java, src/test/java/com/dnd/weddingmap/domain/transaction/controller/TransactionControllerTest.java
None
controller test 코드에서 필요없는 csrf와 accept 설정을 삭제하였습니다.
=> test: delete unnecessary csrf and accept setting

src/test/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java, src/test/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistControllerTest.java, src/test/java/com/dnd/weddingmap/domain/contract/controller/ContractControllerTest.java, src/test/java/com/dnd/weddingmap/domain/transaction/controller/TransactionControllerTest.java
#123 
요청 데이터의 `LocalDate`와 `LocalTime` 데이터 타입을 **String**으로 변경하였습니다.
=> test: change timestamp format

src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/service/impl/ChecklistItemServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/service/impl/ChecklistSubItemServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/checklist/service/impl/ChecklistServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/contract/service/impl/ContractServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/member/service/impl/MemberServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/transaction/service/impl/TransactionServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/wedding/service/impl/WeddingServiceImpl.java
#138 #144 
- 누락된 `@Transactional` 어노테이션 추가
- `@Transactional` 임포트문 수정
- `jakarta.transaction.Transactional` -> `org.springframework.transaction.annotation.Transactional`
- `@Transactional` 옵션 추가
- Read 작업에는 read-only 적용
- CUD 작업에는 rollback 옵션 추가
=> refactor: apply transactional annotation

src/test/java/com/dnd/weddingmap/domain/contract/service/ContractServiceTest.java
None
`ContractService`에 대한 테스트 코드를 추가하였습니다.
=> test: add contract service test

src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/ChecklistItem.java, src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemController.java, src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/service/impl/ChecklistItemServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/ChecklistSubItem.java, src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemController.java, src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/service/impl/ChecklistSubItemServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistController.java, src/main/java/com/dnd/weddingmap/domain/checklist/service/impl/ChecklistServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/contract/Contract.java, src/main/java/com/dnd/weddingmap/domain/contract/controller/ContractController.java, src/main/java/com/dnd/weddingmap/domain/contract/dto/ContractDto.java, src/main/java/com/dnd/weddingmap/domain/contract/dto/ContractListResponseDto.java, src/main/java/com/dnd/weddingmap/domain/contract/service/impl/ContractServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/jwt/controller/JwtController.java, src/main/java/com/dnd/weddingmap/domain/member/Member.java, src/main/java/com/dnd/weddingmap/domain/member/controller/MemberController.java, src/main/java/com/dnd/weddingmap/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/dnd/weddingmap/domain/transaction/Transaction.java, src/main/java/com/dnd/weddingmap/domain/transaction/controller/TransactionController.java, src/main/java/com/dnd/weddingmap/domain/transaction/dto/TransactionDto.java, src/main/java/com/dnd/weddingmap/domain/transaction/dto/TransactionListResponseDto.java, src/main/java/com/dnd/weddingmap/domain/transaction/service/impl/TransactionServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/wedding/Wedding.java, src/main/java/com/dnd/weddingmap/domain/wedding/controller/WeddingController.java
=> refactor: reorder annotations

src/main/java/com/dnd/weddingmap/domain/budget/service/impl/BudgetServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemController.java, src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/service/impl/ChecklistItemServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemController.java, src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/service/impl/ChecklistSubItemServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistController.java, src/main/java/com/dnd/weddingmap/domain/contract/controller/ContractController.java, src/main/java/com/dnd/weddingmap/domain/contract/service/impl/ContractServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/member/controller/MemberController.java, src/main/java/com/dnd/weddingmap/domain/transaction/controller/TransactionController.java, src/main/java/com/dnd/weddingmap/domain/transaction/service/impl/TransactionServiceImpl.java, src/main/java/com/dnd/weddingmap/domain/wedding/controller/WeddingController.java, src/main/java/com/dnd/weddingmap/domain/wedding/service/impl/WeddingServiceImpl.java, src/main/resources/messages.properties, src/test/java/com/dnd/weddingmap/domain/budget/service/BudgetServiceTest.java, src/test/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java, src/test/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java, src/test/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistControllerTest.java, src/test/java/com/dnd/weddingmap/domain/contract/controller/ContractControllerTest.java, src/test/java/com/dnd/weddingmap/domain/contract/service/ContractServiceTest.java, src/test/java/com/dnd/weddingmap/domain/member/controller/MemberControllerTest.java, src/test/java/com/dnd/weddingmap/domain/transaction/controller/TransactionControllerTest.java, src/test/java/com/dnd/weddingmap/domain/transaction/service/TransactionServiceTest.java, src/test/java/com/dnd/weddingmap/domain/wedding/controller/WeddingControllerTest.java, src/test/java/com/dnd/weddingmap/domain/wedding/service/WeddingServiceTest.java, src/test/resources/messages.properties
#157 
* 하드코딩 되어있는 **api response** 및 **exception** message를 `MessageUtil`을 사용하는 방법으로 수정하였습니다.
=> refactor: replace hardcoded messages to message source

src/main/java/com/dnd/weddingmap/domain/member/controller/MemberController.java
None
함수명이 잘못되어 있어 수정하였습니다.
put 메서드를 사용하지 않음에도 함수에는 포함되어 있었습니다.
=> refactor: rename function to upload profile image

src/main/java/com/dnd/weddingmap/domain/jwt/controller/JwtController.java, src/main/java/com/dnd/weddingmap/domain/member/controller/MemberController.java, src/test/java/com/dnd/weddingmap/domain/jwt/controller/JwtControllerTest.java, src/test/java/com/dnd/weddingmap/domain/member/controller/MemberControllerTest.java
#169 
jwt 토큰을 재발급하거나 유저의 프로필 이미지가 업로드된 경우 `201 created`를 반환하도록 수정하였습니다.
=> refactor: return 201 created when resource was created
